// Compiles the site's real stylesheets into one file the design-system
// converter can ship. website/css/ stays the single source of truth —
// styles/twb.css and styles/tokens.css are generated and gitignored.
//
// Order matters and is load-bearing: the remote @import must lead (CSS
// requires @import before any rule), then tokens, then the component layer.
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const webCss = resolve(here, '../../../website/css');
const out = resolve(here, '../styles');
mkdirSync(out, { recursive: true });

const fonts = readFileSync(resolve(out, 'fonts.css'), 'utf8');
const tokens = readFileSync(resolve(webCss, 'tokens.css'), 'utf8');
const site = readFileSync(resolve(webCss, 'site.css'), 'utf8');

// Hoist the @import so it leads the compiled file. NOTE: match the quoted
// url() as a unit — a Google Fonts URL contains semicolons (wght@400;500;600),
// so a naive /@import[^;]+;/ truncates mid-URL and invalidates the whole sheet.
const IMPORT_RE = /@import\s+url\((['"])(?:\\.|(?!\1)[^\\])*\1\)\s*;/g;
const imports = [...fonts.matchAll(IMPORT_RE)].map((m) => m[0]).join('\n');
const fontsRest = fonts.replace(IMPORT_RE, '').trim();

const compiled = [
  '/* TWB Designs — compiled stylesheet. Generated by scripts/sync-css.mjs.',
  '   Source of truth: website/css/tokens.css + website/css/site.css. */',
  imports,
  fontsRest,
  '/* ---- tokens ---- */',
  tokens,
  '/* ---- components ---- */',
  site,
].filter(Boolean).join('\n\n');

writeFileSync(resolve(out, 'twb.css'), compiled);
copyFileSync(resolve(webCss, 'tokens.css'), resolve(out, 'tokens.css'));
console.log(`  compiled styles/twb.css (${(compiled.length / 1024).toFixed(1)} KB)`);
